name: Publish package to the Maven Central Repository
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown

      - name: Update and Install Software
        run: |
          sudo apt update
          sudo ACCEPT_EULA=Y apt -y --fix-missing --allow-downgrades upgrade
          sudo apt -y --allow-downgrades install p7zip-full xdelta3

      - name: Setup Repo
        run: |
          mkdir -p ~/download
          cd ~/download
          touch blank.nds
          gdown 1nyYSx19n_J19X5jsdw5UwBbOCY-BpugM
          7z x "HeartGold (USA).7z"
          xdelta3 -d -s blank.nds "HeartGold (USA).xdelta" HeartGold.nds
          mv "HeartGold.nds" $GITHUB_WORKSPACE
          cd ~

      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode clean deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
