name: Maven Verify
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Update and Install Software
        run: |
          sudo apt update
          sudo ACCEPT_EULA=Y apt -y --fix-missing --allow-downgrades upgrade
          sudo apt -y --allow-downgrades install p7zip-full xdelta3

      - name: Setup Repo
        run: |
          mkdir -p ~/download
          cd ~/download
          touch blank.nds
          wget -c https://drive.google.com/uc?export=download&id=1nyYSx19n_J19X5jsdw5UwBbOCY-BpugM
          7z x "HeartGold (USA).7z"
          xdelta3 -d -s blank.nds "HeartGold (USA).xdelta" HeartGold.nds
          mv "HeartGold.nds" $GITHUB_WORKSPACE
          working-directory: ~

      - uses: actions/checkout@v3
      - name: Checkout
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn verify
